/**
 * server/routes/og.mjs — HTTP handlers for the runtime OG image generator.
 *
 * Routes
 *   GET /og/product/{slug-or-id}-{lang}.png   per-product share card
 *   GET /og/brand/{brand}-{lang}.png          per-brand share card
 *
 * The trailing `-{lang}.png` segment is parsed by the router below so we
 * don't have to register four routes per kind (one per language). Both
 * routes are public, read-only, and cacheable for a long time at the CDN
 * edge — the underlying file is content-addressed by product.updated_at.
 *
 * Why a separate route module (not folded into public-data.mjs):
 *   - Different response type (image/png vs application/json).
 *   - Different cache strategy (long-lived CDN caching here; short-lived
 *     in-memory cache in public-data).
 *   - Keeps the soft-dependency on sharp isolated; if the binary fails
 *     to load only this file's handlers degrade, not the JSON API.
 */

import { getDb } from '../db.mjs';
import {
  getProductOgImage,
  getBrandOgImage,
  isOgImageGenerationAvailable,
  getOgImageGenerationError,
  OG_SUPPORTED_LANGS,
} from '../services/ogImage.mjs';
import { logger } from '../utils/logger.mjs';

const PNG_HEADERS = (cacheKey) => ({
  'Content-Type': 'image/png',
  // Long-lived caching is safe because the cache key (and therefore the
  // generated bytes) only changes when the underlying product changes —
  // and admin saves bust the file by writing a new key. The URL we hand
  // to social platforms includes a `v` query param so they re-crawl on
  // demand if we ever need to force-refresh.
  'Cache-Control': 'public, max-age=2592000, immutable', // 30 days
  'X-OG-Cache-Key': cacheKey,
  'Access-Control-Allow-Origin': '*',
});

const sendError = (res, status, message) => {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ success: false, error: message }));
};

/**
 * Parse `{slug-or-id}-{lang}.png` into its parts. We split on the LAST
 * occurrence of "-" because product slugs themselves can contain "-".
 *
 * Returns { id: 'diox-floor-cleaner', lang: 'ar' } or null.
 */
const parseTrailingLang = (filename) => {
  if (!filename || !filename.endsWith('.png')) return null;
  const stem = filename.slice(0, -4); // strip .png
  const idx = stem.lastIndexOf('-');
  if (idx <= 0) return null;
  const lang = stem.slice(idx + 1).toLowerCase();
  if (!OG_SUPPORTED_LANGS.includes(lang)) return null;
  return { id: stem.slice(0, idx), lang };
};

// ─── GET /og/product/{slug-or-id}-{lang}.png ────────────────────────────────
export const handleProductOg = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/product\/([^/?]+)$/);
  if (!match) {
    sendError(res, 404, 'Not found.');
    return;
  }

  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    sendError(res, 400, 'Invalid path. Expected /og/product/{id}-{lang}.png.');
    return;
  }

  if (!(await isOgImageGenerationAvailable())) {
    logger.warn(
      { err: getOgImageGenerationError() },
      '[og] sharp unavailable — cannot serve dynamic OG image',
    );
    sendError(res, 503, 'OG image generation is unavailable on this deployment.');
    return;
  }

  const db = getDb();
  // Accept either the product's primary key OR a sanitised slug derived
  // from its name. For now we only look up by id — slug routing is added
  // in the same commit as per-product URLs.
  const row = db
    .prepare(`
      SELECT
        id,
        brand,
        name_${parsed.lang}        AS name,
        name_en                    AS name_en,
        description_${parsed.lang} AS description,
        description_en             AS description_en,
        image,
        updated_at
      FROM products
      WHERE id = ? AND active = 1
    `)
    .get(parsed.id);

  if (!row) {
    sendError(res, 404, 'Product not found.');
    return;
  }

  // Fall back to English copy if the requested-language fields are empty
  // (admin frequently authors only Arabic + English first, then localises
  // TR / RU later). Without the fallback the OG card for Russian would
  // render blank text on an otherwise-good background.
  const name = (row.name && row.name.trim()) || row.name_en || row.id;
  const description = (row.description && row.description.trim()) || row.description_en || '';

  // updated_at is a SQLite TEXT column ('YYYY-MM-DD HH:MM:SS'); coerce to
  // an epoch ms so the cache key is monotonic.
  const updatedAtMs = row.updated_at
    ? new Date(row.updated_at.replace(' ', 'T') + 'Z').getTime()
    : 0;

  try {
    const { buffer, cacheKey, fromCache, source, reason } = await getProductOgImage({
      id: row.id,
      name,
      description,
      brand: row.brand,
      lang: parsed.lang,
      updatedAtMs,
      // Pass the product's photo path so the OG generator composites
      // the actual product image (instead of a designed text card).
      // Falls back to the SVG card if the photo can't be loaded.
      imagePath: row.image || null,
    });
    const headers = PNG_HEADERS(cacheKey);
    headers['X-OG-Cache'] = fromCache ? 'HIT' : 'MISS';
    // Surface which path produced the image so an admin debugging
    // "why is my product showing the fallback card?" can curl -I and
    // see X-OG-Source: card vs photo.
    if (source) headers['X-OG-Source'] = source;
    // Reason carries the failure mode when we fell back to the card.
    // Values: '' (success), 'no-image-path', 'photo-load-failed',
    // 'photo-compose-failed'. Empty string is omitted from the header.
    if (reason) headers['X-OG-Reason'] = reason;
    // ImagePath echoed back (truncated) so an admin verifying that
    // the DB has the right path doesn't need to crack open the admin
    // UI. Truncated to 200 chars to keep the header below limits.
    if (row.image) headers['X-OG-ImagePath'] = String(row.image).slice(0, 200);
    res.writeHead(200, headers);
    res.end(buffer);
  } catch (err) {
    // The composite / SVG renderers can throw on edge cases (corrupt
    // photo, missing fontconfig in older deploys, librsvg quirks). We
    // can't let that 500 the share preview — WhatsApp / Facebook /
    // Twitter all need a 200 + valid image bytes or they drop the
    // preview entirely. So we try one final, dependency-light fallback
    // before giving up: a plain solid-colour 1200×630 PNG with the
    // brand's primary colour. No SVG, no font rendering, no compose.
    logger.error(
      { err: { message: err?.message, code: err?.code, stack: err?.stack?.slice(0, 800) }, id: parsed.id, lang: parsed.lang, image: row.image },
      '[og] product render failed — falling back to solid card',
    );
    try {
      const sharp = (await import('sharp')).default;
      const brandColor = row.brand === 'AYLUX'
        ? { r: 122, g: 61, b: 163 } // AYLUX purple
        : { r: 26, g: 77, b: 143 }; // DIOX blue (default)
      const png = await sharp({
        create: {
          width: 1200, height: 630, channels: 4,
          background: { ...brandColor, alpha: 1 },
        },
      }).png().toBuffer();
      res.writeHead(200, {
        ...PNG_HEADERS('emergency-fallback'),
        'X-OG-Source': 'emergency',
        'X-OG-Reason': 'render-threw',
        'X-OG-Error': (err?.message || 'unknown').slice(0, 200),
        'X-OG-ImagePath': row.image ? String(row.image).slice(0, 200) : '(empty)',
      });
      res.end(png);
    } catch (fallbackErr) {
      logger.error({ err: fallbackErr }, '[og] emergency fallback also failed');
      // Give up — return the error message in the JSON so the admin
      // testing this URL in a browser sees what went wrong.
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({
        success: false,
        error: 'OG image render failed.',
        details: err?.message || 'unknown',
        code: err?.code || null,
        imagePath: row.image || null,
      }));
    }
  }
};

// ─── GET /og/debug/product/{id}-{lang}.json ─────────────────────────────────
// Admin-friendly diagnostic that walks the same code path as the PNG
// endpoint but returns JSON describing every step. Public/anonymous on
// purpose: the data is the same the OG endpoint already exposes via
// headers, just easier to read in a browser. Helps debug "why doesn't
// my share preview show the actual photo?" without curl gymnastics.
export const handleProductOgDebug = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/debug\/product\/([^/?]+)$/);
  if (!match) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not found.' }));
    return;
  }
  const parsed = parseTrailingLang(match[1].replace(/\.json$/, ''));
  if (!parsed) {
    res.writeHead(400, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Invalid path. Expected /og/debug/product/{id}-{lang}' }));
    return;
  }

  const sharpAvailable = await isOgImageGenerationAvailable();
  const db = getDb();
  const row = db.prepare(`
    SELECT id, brand,
      name_${parsed.lang}        AS name,
      name_en                    AS name_en,
      description_${parsed.lang} AS description,
      image, updated_at, active
    FROM products WHERE id = ?
  `).get(parsed.id);

  if (!row) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      error: 'Product not found in database.',
      lookedUpId: parsed.id,
      hint: 'Check that the slug in the URL matches a row in the products table.',
    }));
    return;
  }

  // Attempt to load the photo and report what happened — purely
  // diagnostic, no image is generated.
  const { default: sharp } = sharpAvailable ? await import('sharp') : { default: null };
  let photoStatus = { attempted: false, ok: false, bytes: 0, error: null, resolvedUrl: null };
  if (row.image) {
    photoStatus.attempted = true;
    const imagePath = row.image;
    try {
      // Re-implement the resolver here in inline form so we capture
      // the exact intermediate values for the JSON output. Keeps the
      // service code unchanged.
      const trimmed = imagePath.trim();
      if (trimmed.startsWith('/api/uploads/')) {
        photoStatus.resolvedUrl = `local:${trimmed}`;
        const { promises: fs } = await import('node:fs');
        const path = (await import('node:path')).default;
        const { fileURLToPath } = await import('node:url');
        const here = path.dirname(fileURLToPath(import.meta.url));
        const filename = path.basename(trimmed.replace('/api/uploads/', ''));
        const filePath = path.join(here, '..', 'data', 'uploads', filename);
        const stat = await fs.stat(filePath);
        photoStatus.bytes = stat.size;
        photoStatus.ok = stat.isFile() && stat.size > 0;
      } else {
        const STATIC_ORIGIN = (process.env.SITE_URL || 'https://karahoca.com').replace(/\/+$/, '');
        const url = trimmed.startsWith('http') ? trimmed : `${STATIC_ORIGIN}${trimmed.startsWith('/') ? '' : '/'}${trimmed}`;
        photoStatus.resolvedUrl = url;
        const r = await fetch(url, { method: 'HEAD' });
        photoStatus.ok = r.ok;
        photoStatus.status = r.status;
        photoStatus.contentType = r.headers.get('content-type');
        photoStatus.contentLength = r.headers.get('content-length');
      }
    } catch (err) {
      photoStatus.error = err?.message || String(err);
    }
  }

  res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify({
    sharpAvailable,
    sharpError: sharpAvailable ? null : (getOgImageGenerationError()?.message || 'unknown'),
    product: {
      id: row.id,
      brand: row.brand,
      active: row.active,
      hasName: Boolean((row.name || '').trim()),
      hasDescription: Boolean((row.description || '').trim()),
      image: row.image || null,
    },
    photo: photoStatus,
    nextSteps: !sharpAvailable
      ? 'sharp module unavailable — API container needs rebuild with sharp in dependencies.'
      : !row.image
        ? 'Product has no image field. Open /admin/products/' + row.id + ' and upload one.'
        : photoStatus.ok
          ? 'Photo is reachable. The PNG endpoint should now serve a composited image. Try X-OG-Source header on the .png URL.'
          : `Photo at ${photoStatus.resolvedUrl} could not be loaded (${photoStatus.error || photoStatus.status}). Check that the file actually exists.`,
  }, null, 2));
};

// ─── GET /og/brand/{brand}-{lang}.png ───────────────────────────────────────
export const handleBrandOg = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/brand\/([^/?]+)$/);
  if (!match) {
    sendError(res, 404, 'Not found.');
    return;
  }
  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    sendError(res, 400, 'Invalid path. Expected /og/brand/{brand}-{lang}.png.');
    return;
  }

  const brand = parsed.id.toUpperCase();
  if (!['DIOX', 'AYLUX', 'KARAHOCA'].includes(brand)) {
    sendError(res, 404, 'Unknown brand.');
    return;
  }

  if (!(await isOgImageGenerationAvailable())) {
    sendError(res, 503, 'OG image generation is unavailable on this deployment.');
    return;
  }

  try {
    const { buffer, cacheKey, fromCache } = await getBrandOgImage({ brand, lang: parsed.lang });
    const headers = PNG_HEADERS(cacheKey);
    headers['X-OG-Cache'] = fromCache ? 'HIT' : 'MISS';
    res.writeHead(200, headers);
    res.end(buffer);
  } catch (err) {
    logger.error({ err, brand, lang: parsed.lang }, '[og] brand render failed');
    sendError(res, 500, 'OG image render failed.');
  }
};
