/**
 * server/routes/og.mjs — HTTP handlers for the runtime OG image generator.
 *
 * Routes
 *   GET /og/product/{slug-or-id}-{lang}.png   per-product share card
 *   GET /og/brand/{brand}-{lang}.png          per-brand share card
 *
 * The trailing `-{lang}.png` segment is parsed by the router below so we
 * don't have to register four routes per kind (one per language). Both
 * routes are public, read-only, and cacheable for a long time at the CDN
 * edge — the underlying file is content-addressed by product.updated_at.
 *
 * Why a separate route module (not folded into public-data.mjs):
 *   - Different response type (image/png vs application/json).
 *   - Different cache strategy (long-lived CDN caching here; short-lived
 *     in-memory cache in public-data).
 *   - Keeps the soft-dependency on sharp isolated; if the binary fails
 *     to load only this file's handlers degrade, not the JSON API.
 */

import { getDb } from '../db.mjs';
import {
  getProductOgImage,
  getBrandOgImage,
  isOgImageGenerationAvailable,
  getOgImageGenerationError,
  OG_SUPPORTED_LANGS,
} from '../services/ogImage.mjs';
import { logger } from '../utils/logger.mjs';

const PNG_HEADERS = (cacheKey) => ({
  'Content-Type': 'image/png',
  // Long-lived caching is safe because the cache key (and therefore the
  // generated bytes) only changes when the underlying product changes —
  // and admin saves bust the file by writing a new key. The URL we hand
  // to social platforms includes a `v` query param so they re-crawl on
  // demand if we ever need to force-refresh.
  'Cache-Control': 'public, max-age=2592000, immutable', // 30 days
  'X-OG-Cache-Key': cacheKey,
  'Access-Control-Allow-Origin': '*',
});

const sendError = (res, status, message) => {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ success: false, error: message }));
};

/**
 * Parse `{slug-or-id}-{lang}.png` into its parts. We split on the LAST
 * occurrence of "-" because product slugs themselves can contain "-".
 *
 * Returns { id: 'diox-floor-cleaner', lang: 'ar' } or null.
 */
const parseTrailingLang = (filename) => {
  if (!filename || !filename.endsWith('.png')) return null;
  const stem = filename.slice(0, -4); // strip .png
  const idx = stem.lastIndexOf('-');
  if (idx <= 0) return null;
  const lang = stem.slice(idx + 1).toLowerCase();
  if (!OG_SUPPORTED_LANGS.includes(lang)) return null;
  return { id: stem.slice(0, idx), lang };
};

// ─── GET /og/product/{slug-or-id}-{lang}.png ────────────────────────────────
export const handleProductOg = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/product\/([^/?]+)$/);
  if (!match) {
    sendError(res, 404, 'Not found.');
    return;
  }

  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    sendError(res, 400, 'Invalid path. Expected /og/product/{id}-{lang}.png.');
    return;
  }

  if (!(await isOgImageGenerationAvailable())) {
    logger.warn(
      { err: getOgImageGenerationError() },
      '[og] sharp unavailable — cannot serve dynamic OG image',
    );
    sendError(res, 503, 'OG image generation is unavailable on this deployment.');
    return;
  }

  const db = getDb();
  // Accept either the product's primary key OR a sanitised slug derived
  // from its name. For now we only look up by id — slug routing is added
  // in the same commit as per-product URLs.
  const row = db
    .prepare(`
      SELECT
        id,
        brand,
        name_${parsed.lang}        AS name,
        name_en                    AS name_en,
        description_${parsed.lang} AS description,
        description_en             AS description_en,
        image,
        updated_at
      FROM products
      WHERE id = ? AND active = 1
    `)
    .get(parsed.id);

  if (!row) {
    sendError(res, 404, 'Product not found.');
    return;
  }

  // Fall back to English copy if the requested-language fields are empty
  // (admin frequently authors only Arabic + English first, then localises
  // TR / RU later). Without the fallback the OG card for Russian would
  // render blank text on an otherwise-good background.
  const name = (row.name && row.name.trim()) || row.name_en || row.id;
  const description = (row.description && row.description.trim()) || row.description_en || '';

  // updated_at is a SQLite TEXT column ('YYYY-MM-DD HH:MM:SS'); coerce to
  // an epoch ms so the cache key is monotonic.
  const updatedAtMs = row.updated_at
    ? new Date(row.updated_at.replace(' ', 'T') + 'Z').getTime()
    : 0;

  try {
    const { buffer, cacheKey, fromCache, source } = await getProductOgImage({
      id: row.id,
      name,
      description,
      brand: row.brand,
      lang: parsed.lang,
      updatedAtMs,
      // Pass the product's photo path so the OG generator composites
      // the actual product image (instead of a designed text card).
      // Falls back to the SVG card if the photo can't be loaded.
      imagePath: row.image || null,
    });
    const headers = PNG_HEADERS(cacheKey);
    headers['X-OG-Cache'] = fromCache ? 'HIT' : 'MISS';
    // Surface which path produced the image so an admin debugging
    // "why is my product showing the fallback card?" can curl -I and
    // see X-OG-Source: card vs photo.
    if (source) headers['X-OG-Source'] = source;
    res.writeHead(200, headers);
    res.end(buffer);
  } catch (err) {
    logger.error({ err, id: parsed.id, lang: parsed.lang }, '[og] product render failed');
    sendError(res, 500, 'OG image render failed.');
  }
};

// ─── GET /og/brand/{brand}-{lang}.png ───────────────────────────────────────
export const handleBrandOg = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/brand\/([^/?]+)$/);
  if (!match) {
    sendError(res, 404, 'Not found.');
    return;
  }
  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    sendError(res, 400, 'Invalid path. Expected /og/brand/{brand}-{lang}.png.');
    return;
  }

  const brand = parsed.id.toUpperCase();
  if (!['DIOX', 'AYLUX', 'KARAHOCA'].includes(brand)) {
    sendError(res, 404, 'Unknown brand.');
    return;
  }

  if (!(await isOgImageGenerationAvailable())) {
    sendError(res, 503, 'OG image generation is unavailable on this deployment.');
    return;
  }

  try {
    const { buffer, cacheKey, fromCache } = await getBrandOgImage({ brand, lang: parsed.lang });
    const headers = PNG_HEADERS(cacheKey);
    headers['X-OG-Cache'] = fromCache ? 'HIT' : 'MISS';
    res.writeHead(200, headers);
    res.end(buffer);
  } catch (err) {
    logger.error({ err, brand, lang: parsed.lang }, '[og] brand render failed');
    sendError(res, 500, 'OG image render failed.');
  }
};
