/**
 * server/routes/og.mjs — HTTP handlers for the runtime OG image generator.
 *
 * Routes
 *   GET /og/product/{slug-or-id}-{lang}.png   per-product share card
 *   GET /og/brand/{brand}-{lang}.png          per-brand share card
 *
 * The trailing `-{lang}.png` segment is parsed by the router below so we
 * don't have to register four routes per kind (one per language). Both
 * routes are public, read-only, and cacheable for a long time at the CDN
 * edge — the underlying file is content-addressed by product.updated_at.
 *
 * Why a separate route module (not folded into public-data.mjs):
 *   - Different response type (image/png vs application/json).
 *   - Different cache strategy (long-lived CDN caching here; short-lived
 *     in-memory cache in public-data).
 *   - Keeps the soft-dependency on sharp isolated; if the binary fails
 *     to load only this file's handlers degrade, not the JSON API.
 */

import { getDb } from '../db.mjs';
import {
  getProductOgImage,
  getBrandOgImage,
  isOgImageGenerationAvailable,
  getOgImageGenerationError,
  OG_SUPPORTED_LANGS,
} from '../services/ogImage.mjs';
import { logger } from '../utils/logger.mjs';

const PNG_HEADERS = (cacheKey) => ({
  'Content-Type': 'image/png',
  // Long-lived caching is safe because the cache key (and therefore the
  // generated bytes) only changes when the underlying product changes —
  // and admin saves bust the file by writing a new key. The URL we hand
  // to social platforms includes a `v` query param so they re-crawl on
  // demand if we ever need to force-refresh.
  'Cache-Control': 'public, max-age=2592000, immutable', // 30 days
  'X-OG-Cache-Key': cacheKey,
  'Access-Control-Allow-Origin': '*',
});

const sendError = (res, status, message) => {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ success: false, error: message }));
};

/**
 * HTTP header values must be ASCII per RFC 7230. Any non-ASCII byte
 * (Arabic / Cyrillic / emoji / accented Latin) makes Node throw
 * ERR_INVALID_CHAR from res.writeHead.
 *
 * KARAHOCA product image paths in the DB routinely contain Arabic
 * (e.g. "/diox-images/ديوكس سوبر جل.png"), so any diagnostic header
 * we set from that data must be safely encoded first. We use
 * encodeURIComponent which produces a deterministic ASCII string the
 * admin can decode back via `decodeURIComponent` if they need the
 * original.
 *
 * The 200-char cap is preserved — encoded UTF-8 inflates by ~3x for
 * Arabic, so a 200-char raw path becomes a ~600-char encoded one;
 * we slice AFTER encoding to keep the wire size predictable.
 */
const asciiHeaderValue = (s) => {
  if (s == null) return '';
  const str = String(s);
  if (/^[\x20-\x7E]*$/.test(str)) return str.slice(0, 600);
  return encodeURIComponent(str).slice(0, 600);
};

/**
 * Parse `{slug-or-id}-{lang}.{ext}` into its parts. We split on the LAST
 * occurrence of "-" because product slugs themselves can contain "-".
 *
 * Accepts EITHER:
 *   - filenames with explicit extension: 'diox-floor-cleaner-ar.png'
 *   - bare stem (no extension): 'diox-floor-cleaner-ar' — used by the
 *     debug endpoint which formats its URL as `…/{stem}.json` and
 *     strips the .json before calling here.
 *
 * Returns { id: 'diox-floor-cleaner', lang: 'ar' } or null.
 */
const parseTrailingLang = (filename) => {
  if (!filename) return null;
  // Strip any recognised extension. We accept .png because that's the
  // canonical share-card URL; .webp / .json / no-extension all parse
  // the same way once the stem is isolated.
  let stem = filename;
  for (const ext of ['.png', '.webp', '.json']) {
    if (stem.endsWith(ext)) { stem = stem.slice(0, -ext.length); break; }
  }
  const idx = stem.lastIndexOf('-');
  if (idx <= 0) return null;
  const lang = stem.slice(idx + 1).toLowerCase();
  if (!OG_SUPPORTED_LANGS.includes(lang)) return null;
  return { id: stem.slice(0, idx), lang };
};

// ─── GET /og/product/{slug-or-id}-{lang}.png ────────────────────────────────
export const handleProductOg = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/product\/([^/?]+)$/);
  if (!match) {
    sendError(res, 404, 'Not found.');
    return;
  }

  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    sendError(res, 400, 'Invalid path. Expected /og/product/{id}-{lang}.png.');
    return;
  }

  if (!(await isOgImageGenerationAvailable())) {
    logger.warn(
      { err: getOgImageGenerationError() },
      '[og] sharp unavailable — cannot serve dynamic OG image',
    );
    sendError(res, 503, 'OG image generation is unavailable on this deployment.');
    return;
  }

  const db = getDb();
  // Accept either the product's primary key OR a sanitised slug derived
  // from its name. For now we only look up by id — slug routing is added
  // in the same commit as per-product URLs.
  const row = db
    .prepare(`
      SELECT
        id,
        brand,
        name_${parsed.lang}        AS name,
        name_en                    AS name_en,
        description_${parsed.lang} AS description,
        description_en             AS description_en,
        image,
        updated_at
      FROM products
      WHERE id = ? AND active = 1
    `)
    .get(parsed.id);

  if (!row) {
    sendError(res, 404, 'Product not found.');
    return;
  }

  // Fall back to English copy if the requested-language fields are empty
  // (admin frequently authors only Arabic + English first, then localises
  // TR / RU later). Without the fallback the OG card for Russian would
  // render blank text on an otherwise-good background.
  const name = (row.name && row.name.trim()) || row.name_en || row.id;
  const description = (row.description && row.description.trim()) || row.description_en || '';

  // updated_at is a SQLite TEXT column ('YYYY-MM-DD HH:MM:SS'); coerce to
  // an epoch ms so the cache key is monotonic.
  const updatedAtMs = row.updated_at
    ? new Date(row.updated_at.replace(' ', 'T') + 'Z').getTime()
    : 0;

  try {
    const { buffer, cacheKey, fromCache, source, reason } = await getProductOgImage({
      id: row.id,
      name,
      description,
      brand: row.brand,
      lang: parsed.lang,
      updatedAtMs,
      // Pass the product's photo path so the OG generator composites
      // the actual product image (instead of a designed text card).
      // Falls back to the SVG card if the photo can't be loaded.
      imagePath: row.image || null,
    });
    const headers = PNG_HEADERS(cacheKey);
    headers['X-OG-Cache'] = fromCache ? 'HIT' : 'MISS';
    // Surface which path produced the image so an admin debugging
    // "why is my product showing the fallback card?" can curl -I and
    // see X-OG-Source: card vs photo.
    if (source) headers['X-OG-Source'] = source;
    // Reason carries the failure mode when we fell back to the card.
    // Values: '' (success), 'no-image-path', 'photo-load-failed',
    // 'photo-compose-failed'. Empty string is omitted from the header.
    if (reason) headers['X-OG-Reason'] = reason;
    // ImagePath echoed back (truncated + percent-encoded if Arabic /
    // Cyrillic / etc.) — admin can decodeURIComponent() to read it.
    // RAW non-ASCII bytes in a header value crash Node's writeHead
    // with ERR_INVALID_CHAR, so the asciiHeaderValue helper is
    // load-bearing here for products with localised filenames.
    if (row.image) headers['X-OG-ImagePath'] = asciiHeaderValue(row.image);
    res.writeHead(200, headers);
    res.end(buffer);
  } catch (err) {
    // The composite / SVG renderers can throw on edge cases (corrupt
    // photo, missing fontconfig in older deploys, librsvg quirks). We
    // can't let that 500 the share preview — WhatsApp / Facebook /
    // Twitter all need a 200 + valid image bytes or they drop the
    // preview entirely. So we try one final, dependency-light fallback
    // before giving up: a plain solid-colour 1200×630 PNG with the
    // brand's primary colour. No SVG, no font rendering, no compose.
    logger.error(
      { err: { message: err?.message, code: err?.code, stack: err?.stack?.slice(0, 800) }, id: parsed.id, lang: parsed.lang, image: row.image },
      '[og] product render failed — falling back to solid card',
    );
    try {
      const sharp = (await import('sharp')).default;
      const brandColor = row.brand === 'AYLUX'
        ? { r: 122, g: 61, b: 163 } // AYLUX purple
        : { r: 26, g: 77, b: 143 }; // DIOX blue (default)
      const png = await sharp({
        create: {
          width: 1200, height: 630, channels: 4,
          background: { ...brandColor, alpha: 1 },
        },
      }).png().toBuffer();
      res.writeHead(200, {
        ...PNG_HEADERS('emergency-fallback'),
        'X-OG-Source': 'emergency',
        'X-OG-Reason': 'render-threw',
        // err.message may contain non-ASCII for fs/network errors that
        // include the offending path — wrap through asciiHeaderValue
        // so the emergency fallback never repeats the original
        // ERR_INVALID_CHAR crash from the primary path.
        'X-OG-Error': asciiHeaderValue(err?.message || 'unknown'),
        'X-OG-ImagePath': row.image ? asciiHeaderValue(row.image) : '(empty)',
      });
      res.end(png);
    } catch (fallbackErr) {
      logger.error({ err: fallbackErr }, '[og] emergency fallback also failed');
      // Give up — return the error message in the JSON so the admin
      // testing this URL in a browser sees what went wrong.
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({
        success: false,
        error: 'OG image render failed.',
        details: err?.message || 'unknown',
        code: err?.code || null,
        imagePath: row.image || null,
      }));
    }
  }
};

// ─── GET /og/debug/product/{id}-{lang}.json ─────────────────────────────────
// Admin-friendly diagnostic that walks the same code path as the PNG
// endpoint but returns JSON describing every step. Public/anonymous on
// purpose: the data is the same the OG endpoint already exposes via
// headers, just easier to read in a browser. Helps debug "why doesn't
// my share preview show the actual photo?" without curl gymnastics.
export const handleProductOgDebug = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/debug\/product\/([^/?]+)$/);
  if (!match) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not found.' }));
    return;
  }
  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    res.writeHead(400, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      error: 'Invalid path. Expected /og/debug/product/{id}-{lang}[.json]',
      received: match[1],
      supportedLangs: OG_SUPPORTED_LANGS,
    }));
    return;
  }

  const sharpAvailable = await isOgImageGenerationAvailable();
  const db = getDb();
  const row = db.prepare(`
    SELECT id, brand,
      name_${parsed.lang}        AS name,
      name_en                    AS name_en,
      description_${parsed.lang} AS description,
      image, updated_at, active
    FROM products WHERE id = ?
  `).get(parsed.id);

  if (!row) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      error: 'Product not found in database.',
      lookedUpId: parsed.id,
      hint: 'Check that the slug in the URL matches a row in the products table.',
    }));
    return;
  }

  // Attempt to load the photo and report what happened — purely
  // diagnostic, no image is generated.
  const { default: sharp } = sharpAvailable ? await import('sharp') : { default: null };
  let photoStatus = { attempted: false, ok: false, bytes: 0, error: null, resolvedUrl: null };
  if (row.image) {
    photoStatus.attempted = true;
    const imagePath = row.image;
    try {
      // Re-implement the resolver here in inline form so we capture
      // the exact intermediate values for the JSON output. Keeps the
      // service code unchanged.
      const trimmed = imagePath.trim();
      if (trimmed.startsWith('/api/uploads/')) {
        photoStatus.resolvedUrl = `local:${trimmed}`;
        const { promises: fs } = await import('node:fs');
        const path = (await import('node:path')).default;
        const { fileURLToPath } = await import('node:url');
        const here = path.dirname(fileURLToPath(import.meta.url));
        const filename = path.basename(trimmed.replace('/api/uploads/', ''));
        const filePath = path.join(here, '..', 'data', 'uploads', filename);
        const stat = await fs.stat(filePath);
        photoStatus.bytes = stat.size;
        photoStatus.ok = stat.isFile() && stat.size > 0;
      } else {
        const STATIC_ORIGIN = (process.env.SITE_URL || 'https://karahoca.com').replace(/\/+$/, '');
        const rawUrl = trimmed.startsWith('http') ? trimmed : `${STATIC_ORIGIN}${trimmed.startsWith('/') ? '' : '/'}${trimmed}`;
        // Percent-encode non-ASCII (Arabic, Cyrillic) so fetch sends a
        // valid HTTP request. Without this, an admin storing
        // "/diox-images/ديوكس سوبر جل.png" in DB causes the upstream
        // to receive raw UTF-8 in the path and 404 inconsistently.
        const url = new URL(rawUrl).toString();
        photoStatus.resolvedUrl = url;
        photoStatus.rawUrl = rawUrl;

        // Try the original URL first…
        const r = await fetch(url, { method: 'HEAD' });
        photoStatus.ok = r.ok;
        photoStatus.status = r.status;
        photoStatus.contentType = r.headers.get('content-type');
        photoStatus.contentLength = r.headers.get('content-length');

        // …then probe the .webp sibling, the same way the runtime
        // generator does, so the debug endpoint reports the EFFECTIVE
        // status rather than just the literal-path 404.
        if (!r.ok) {
          const lastDot = url.lastIndexOf('.');
          if (lastDot > url.lastIndexOf('/')) {
            const ext = url.slice(lastDot + 1).toLowerCase();
            if (ext === 'png' || ext === 'jpg' || ext === 'jpeg') {
              const webpUrl = url.slice(0, lastDot) + '.webp';
              const r2 = await fetch(webpUrl, { method: 'HEAD' });
              photoStatus.webpFallback = {
                url: webpUrl,
                ok: r2.ok,
                status: r2.status,
                contentType: r2.headers.get('content-type'),
              };
              if (r2.ok) photoStatus.ok = true;
            }
          }
        }
      }
    } catch (err) {
      photoStatus.error = err?.message || String(err);
    }
  }

  res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify({
    sharpAvailable,
    sharpError: sharpAvailable ? null : (getOgImageGenerationError()?.message || 'unknown'),
    product: {
      id: row.id,
      brand: row.brand,
      active: row.active,
      hasName: Boolean((row.name || '').trim()),
      hasDescription: Boolean((row.description || '').trim()),
      image: row.image || null,
    },
    photo: photoStatus,
    nextSteps: !sharpAvailable
      ? 'sharp module unavailable — API container needs rebuild with sharp in dependencies.'
      : !row.image
        ? 'Product has no image field. Open /admin/products/' + row.id + ' and upload one.'
        : photoStatus.ok
          ? 'Photo is reachable. The PNG endpoint should now serve a composited image. Try X-OG-Source header on the .png URL.'
          : `Photo at ${photoStatus.resolvedUrl} could not be loaded (${photoStatus.error || photoStatus.status}). Check that the file actually exists.`,
  }, null, 2));
};

// ─── GET /og/brand/{brand}-{lang}.png ───────────────────────────────────────
export const handleBrandOg = async (req, res, ctx) => {
  const match = ctx.url.match(/^\/og\/brand\/([^/?]+)$/);
  if (!match) {
    sendError(res, 404, 'Not found.');
    return;
  }
  const parsed = parseTrailingLang(match[1]);
  if (!parsed) {
    sendError(res, 400, 'Invalid path. Expected /og/brand/{brand}-{lang}.png.');
    return;
  }

  const brand = parsed.id.toUpperCase();
  if (!['DIOX', 'AYLUX', 'KARAHOCA'].includes(brand)) {
    sendError(res, 404, 'Unknown brand.');
    return;
  }

  if (!(await isOgImageGenerationAvailable())) {
    sendError(res, 503, 'OG image generation is unavailable on this deployment.');
    return;
  }

  try {
    const { buffer, cacheKey, fromCache } = await getBrandOgImage({ brand, lang: parsed.lang });
    const headers = PNG_HEADERS(cacheKey);
    headers['X-OG-Cache'] = fromCache ? 'HIT' : 'MISS';
    res.writeHead(200, headers);
    res.end(buffer);
  } catch (err) {
    logger.error({ err, brand, lang: parsed.lang }, '[og] brand render failed');
    sendError(res, 500, 'OG image render failed.');
  }
};
