/**
 * Image optimization utilities.
 *
 * Converts image paths from legacy formats (.png, .jpg, .jpeg) to
 * optimized WebP format. Original files are preserved on disk — this
 * only rewrites the URL the browser requests.
 */

const CONVERTIBLE_RE = /\.(png|jpe?g)$/i;

/**
 * Rewrite an image path so the browser fetches the WebP version
 * that was generated by `scripts/optimize-images.mjs`.
 *
 * - `/logos/altunsa-logo.png`  → `/logos/altunsa-logo.webp`
 * - `/aylux/product.jpg`      → `/aylux/product.webp`
 * - `/already-fine.webp`      → `/already-fine.webp` (no-op)
 * - External URLs (http/data) → returned unchanged
 */
export function toWebp(src: string | undefined | null): string {
  if (!src) return '';
  // Don't touch external URLs or data URIs
  if (src.startsWith('http') || src.startsWith('data:')) return src;
  return src.replace(CONVERTIBLE_RE, '.webp');
}
